### ISSUE TITLE
Sublime Version 3.2.2

### ISSUE THREAD

**Issue by dustinsummers** [QuinnWilton/sublime-smali#10]
Do we know if this highlighting still works with Sublime Version 3.2.2?  The Syntax still shows up in the dropdown menu, but it doesn't seem to actually be applying any type of syntax highlighting?

The highlighting works for every other language...

![Screen Shot 2019-11-11 at 5 42 44 PM](https://user-images.githubusercontent.com/25121655/68627026-b7091a80-04aa-11ea-91e3-586c0a88ac79.png)
![Screen Shot 2019-11-11 at 5 42 38 PM](https://user-images.githubusercontent.com/25121655/68627034-b96b7480-04aa-11ea-9b5c-36f5af951582.png)

**Comment by CalebFenton** [comment]
I just tested it on 3.2.2 and it still works. Your problem is that you've opened what appears to be a dexdump file which has some smali-looking stuff inside it. Try using baksmali and opening some `.smali` files.
