### ISSUE TITLE
A syntax and grammar checker is required

### ISSUE THREAD

**Issue by huanghe2015** [QuinnWilton/sublime-smali#9]
Even though your plugin can achieve syntax highlight in editor,but furthermore we need to check syntax and grammar correctness for our file in text editor automatically,so we need a plugin to do this.
Can you help this?

**Comment by CalebFenton** [comment]
Please explain in more detail what you want.

**Comment by huanghe2015** [comment]
I had updated my initial content,so check it out.

**Comment by CalebFenton** [comment]
This plugin checks grammar a quit a bit already. If you need something more, use this gammar: https://github.com/JesusFreke/smali/tree/master/smali/src/main/antlr
